调整网站介绍与关于页面。
FZUG/fzug.github.io pull request #1
Opened 2017-12-15 15:10 UTC by sztsian

Signed-off-by: Zamir SUN <sztsian@gmail.com>

2017-12-15 16:10 UTC, alick requested changes

2017-12-15 16:10 UTC, alick commented on _config.yml
> +  Fedora 中文用户组（Fedora Chinese User Group，简写FZUG），是面向中文用户的 Fedora 用户组。
中英文之间加空格

2017-12-15 16:10 UTC, alick commented on about.md
> +IRC: #fedora-zh (IRC服务器:freenode.net)
第二个冒号

2018-01-03 00:53 UTC, robberphex approved these changes

2018-01-03 00:54 UTC, merged