Slime for fedora感谢指正，我已修改
FZUG/fzug.github.io pull request #13
Opened 2018-03-28 16:00 UTC by shiptux

如有不当之处，还请指教。

2018-03-28 17:05 UTC, alick commented on _posts/2018-03-24-how-to-creat-pull-request.md
> +windows用户可以使用终端登录的工具来生成，linux下直接使用命令
Windows, Linux, Fedora, Git, ... 首字母大写

2018-03-28 17:07 UTC, alick commented on _posts/2018-03-24-how-to-creat-pull-request.md
> +2. 使用sshclone并尝试push操作
使用 SSH 克隆……（注意空格，还有翻译的一致性）

2018-03-28 17:07 UTC, alick commented on _posts/2018-03-24-how-to-creat-pull-request.md
> +并不需要输入密码
还是建议这个部分单独发 PR，不要和新文章混在一块儿

2018-03-28 17:10 UTC, alick commented on _posts/2018-03-28-Slime-for-fedora.md
> +lisp所遵循的规范。[^1]
HTML 里很少用到脚注。用脚注来引用参考文献也不常见。感觉这里完全可以用自己的话重写。或者说：根据百度百科（此处有链接），“引用部分”

2018-03-28 17:11 UTC, alick commented on _posts/2018-03-28-Slime-for-fedora.md
> +使用<code>M-x package-refresh-contents<code>更新之后 使用<code>M-x package-install slime<code> 安装slime
也许解释一下 M 是 Alt 键？毕竟是面向新手的。

2018-03-28 17:13 UTC, alick commented
另外，修改之后不需要关闭现有 PR 另开新 PR，直接 push 到原来的分支，这个 PR 里的信息会更新的。

2018-03-28 17:39 UTC, alick requested changes
请依评论修订

2018-03-29 12:16 UTC, shiptux commented on _posts/2018-03-24-how-to-creat-pull-request.md
> +windows用户可以使用终端登录的工具来生成，linux下直接使用命令
这部分已经更改。

2018-03-29 12:20 UTC, shiptux commented on _posts/2018-03-28-Slime-for-fedora.md
> +使用<code>M-x package-refresh-contents<code>更新之后 使用<code>M-x package-install slime<code> 安装slime
加上这个也对。

2018-03-29 12:20 UTC, shiptux commented on _posts/2018-03-28-Slime-for-fedora.md
> +lisp所遵循的规范。[^1]
已经使用自己的话语进行重写。

2018-03-29 12:20 UTC, shiptux commented on _posts/2018-03-24-how-to-creat-pull-request.md
> +并不需要输入密码
这个操作是我先删除我的这部分内容，然后 git push 之后再 pull request ，等待成功之后再加上这部分重新执行以上操作吗？ 这个过程对吗？

2018-03-29 12:20 UTC, shiptux commented on _posts/2018-03-24-how-to-creat-pull-request.md
> +2. 使用sshclone并尝试push操作
好的，命令部分一般大写吗还是缩写的命令需要大写？

2018-03-29 12:21 UTC, shiptux commented
谢谢 Alick 宝贵的建议。

2018-03-29 22:37 UTC, alick commented on _posts/2018-03-24-how-to-creat-pull-request.md
> +并不需要输入密码
记得删除时备份内容。提交后之后直接 `git push`。之后有两个选择：1) 在现有 FZUG master 分支基础上新建分支，加上习题解答部分，提交 push 到新分支再发 PR；2) 等待这个slime PR 合并后更新本地的 master 分支到最新，再发新的关于这个习题解答的 PR

2018-03-29 22:39 UTC, alick commented on _posts/2018-03-28-Slime-for-fedora.md
> +lisp所遵循的规范。[^1]
没有看到重写后的样子。也许你忘了 push 这些 commit？

2018-03-30 14:12 UTC, shiptux commented on _posts/2018-03-24-how-to-creat-pull-request.md
> +并不需要输入密码
我选择第二种方式吧。

2018-03-30 17:22 UTC, alick requested changes
抱歉再打扰你一次：注意那些图片也是习题解答的内容，请一并移走。

2018-03-30 17:23 UTC, alick commented on _posts/2018-03-24-how-to-creat-pull-request.md
> -
请把这个删掉的空行补回来 :smiley_cat:

2018-04-02 08:41 UTC, shiptux commented
已在136行添加空行

2018-04-02 16:15 UTC, alick commented
空行并没有添加上……

2018-04-03 16:03 UTC, alick approved these changes

2018-04-03 16:04 UTC, merged

2018-04-03 16:07 UTC, alick commented
已经合并，感谢投稿！后面如需任何修订，请以当前 master 分支为基础 fork