Add How Fedora Secures Package Delivery
FZUG/fzug.github.io pull request #15
Opened 2018-04-05 03:38 UTC by sztsian

Signed-off-by: Zamir SUN <sztsian@gmail.com>

2018-04-05 04:13 UTC, alick commented on _posts/2018-04-05-fedora-secures-package-delivery
> +这儿我们要讨论下 “相对较新 (reasonable fresh) ” 这个部分。仓库每天被构建，校验值发送后最多保留 3 天。这样确保稍稍滞后的镜像源不会立马被标记为无效。
括号内全英文/半角的话括号也用半角括号

2018-04-05 04:14 UTC, alick commented on _posts/2018-04-05-fedora-secures-package-delivery
> +Fedora Project 发布的所有 RPM 包都使用 GPG 进行签名。 DNF (或者 YUM) 在从设置为 `gpgcheck=1` 的仓库中安装软件包时会验证软件包的签名，而这个设置在 Fedora 安装后是默认的。如果你从仓库之外安装软件包，例如手动下载，将不会自动检查签名。然而，可以手动通过 `rpm -K 文件名.rpm` 使用已经导入的 GPG 签名证书进行检查。
Project 不翻译吗？

2018-04-05 04:16 UTC, alick commented on _posts/2018-04-05-fedora-secures-package-delivery
> +据此，对软件包进行签名能防止软件包被修改，或者被提供了一个完全不同的软件包。但仍不能防止“休克攻击”或者有害的软件仓库信息。
休克攻击？freeze attack
有害->恶意

2018-04-05 04:17 UTC, alick requested changes
有些疑问和建议

2018-04-05 04:26 UTC, sztsian commented on _posts/2018-04-05-fedora-secures-package-delivery
> +这儿我们要讨论下 “相对较新 (reasonable fresh) ” 这个部分。仓库每天被构建，校验值发送后最多保留 3 天。这样确保稍稍滞后的镜像源不会立马被标记为无效。
全英文那几处确实是半角啊！

2018-04-05 04:27 UTC, sztsian commented on _posts/2018-04-05-fedora-secures-package-delivery
> +Fedora Project 发布的所有 RPM 包都使用 GPG 进行签名。 DNF (或者 YUM) 在从设置为 `gpgcheck=1` 的仓库中安装软件包时会验证软件包的签名，而这个设置在 Fedora 安装后是默认的。如果你从仓库之外安装软件包，例如手动下载，将不会自动检查签名。然而，可以手动通过 `rpm -K 文件名.rpm` 使用已经导入的 GPG 签名证书进行检查。
原文 Fedora Project ， 我觉得既然是首字母大写了，应该作为专有名词予以保留吧

2018-04-05 21:16 UTC, alick commented on _posts/2018-04-05-fedora-secures-package-delivery
> +Fedora Project 发布的所有 RPM 包都使用 GPG 进行签名。 DNF (或者 YUM) 在从设置为 `gpgcheck=1` 的仓库中安装软件包时会验证软件包的签名，而这个设置在 Fedora 安装后是默认的。如果你从仓库之外安装软件包，例如手动下载，将不会自动检查签名。然而，可以手动通过 `rpm -K 文件名.rpm` 使用已经导入的 GPG 签名证书进行检查。
这里并没有特殊含义。曼哈顿计划就是 Manhattan Project

2018-04-05 21:17 UTC, alick commented on _posts/2018-04-05-fedora-secures-package-delivery
> +这儿我们要讨论下 “相对较新 (reasonable fresh) ” 这个部分。仓库每天被构建，校验值发送后最多保留 3 天。这样确保稍稍滞后的镜像源不会立马被标记为无效。
哦，我看错了

2018-04-05 21:18 UTC, alick commented on _posts/2018-04-05-fedora-secures-package-delivery
> +据此，对软件包进行签名能防止软件包被修改，或者被提供了一个完全不同的软件包。但仍不能防止“ freeze attack ”或者恶意的软件仓库信息。
你可能误会了。我只是觉得 freeze 不是休克的意思，freeze attack 能翻译还是尽量翻译，可以加英文备注

2018-04-06 02:16 UTC, alick commented on _posts/2018-04-05-fedora-secures-package-delivery
> +虽然多次有人请求，但是 Fedora 项目（至今）尚未对仓库进行签名。一个主要原因是 DBF/YUM 仓库信息缺少一个类似 "ValidUntil" （有效期）这样的属性。此外，DNF 下载和验证仓库信息使用的库 librepo 会将失效的 GPG 签名视作有效。这意味着迄今完全没有办法将仓库标记为只有一段有效期。
DBF=>DNF

2018-04-06 02:17 UTC, alick commented on _posts/2018-04-05-fedora-secures-package-delivery
> +今年早些时候， packagecloud 发布了一篇名为 [“attacks against GPG signed APT repositories” （针对启用了 GPG 签名的 ATP 仓库的攻击）](https://blog.packagecloud.io/eng/2018/02/21/attacks-against-secure-apt-repositories/)的文章。当前，Fedo
ATP->APT

2018-04-06 02:18 UTC, alick requested changes
some typos

2018-04-07 03:24 UTC, alick commented on _posts/2018-04-05-fedora-secures-package-delivery
> +当这个按钮被电击，所有不包含最新仓库信息的镜像都会被认为是已经过期的。这确保 Fedora 用户尽快获得安全补丁。然而在一小段时间内仅有主源被标记为可信，直到其他镜像完成了数据同步。采取这个解决方案从而免得重要的修复被拖延导致的用户在该时间内受到攻击的风险。
电击->点击

2018-04-07 03:25 UTC, alick commented on _posts/2018-04-05-fedora-secures-package-delivery
> +据此，对软件包进行签名能防止软件包被修改，或者被提供了一个完全不同的软件包。但仍不能防止“冷冻攻击 (freeze attack) ”或者恶意的软件仓库信息。
freeze attack 感觉“冻结攻击”更好。是冻结软件仓库为某一版本阻止用户更新的意思。

2018-04-07 03:26 UTC, alick requested changes
抱歉，又发现了typo

2018-04-07 03:33 UTC, alick approved these changes

2018-04-07 03:33 UTC, merged