添加新文章「Fedora 模块化 (Modularity) 的前世今生」
FZUG/fzug.github.io pull request #16
Opened 2018-04-07 04:57 UTC by geekpany

Signed-off-by: Pany <pany@fedoraproject.org>

2018-04-07 16:13 UTC, alick commented
@geekpany 像你所说的，这篇文章可能已经有点过时了。F28 beta 里 modularity 应该已经是一个主要特性了。建议参考比对下 F28 beta 宣传文案里的内容，看下是否过时

2018-04-08 04:46 UTC, geekpany commented
@alick 从 <https://fedoraproject.org/wiki/Changes/F28AddonModularity> 来看，是直接给出了文章链接：

> Summary
>
> Beginning in Fedora 28, Fedora will provide a new set of repositories for software and updates with alternative versions from those shipped in the default release.
> 
> Please see [Modularity is Dead, Long Live Modularity!](https://communityblog.fedoraproject.org/modularity-dead-long-live-modularity/) for an in-depth description of the plan. 

不知道我有没有漏掉什么。

如果已经没有时效性了，那我就关闭掉了。

2018-04-08 04:50 UTC, sztsian commented
我觉得这篇文章没过时。这是 Modularity 发生策略变化之后写的，现在的 Modularity 就是本文描述的思路。 Ref https://fedoramagazine.org/announcing-fedora-28-beta/

2018-04-11 09:26 UTC, geekpany commented
我添加了一些更新的内容， @alick  和 @sztsian 麻烦帮忙看一下有没有什么要补充的吧

2018-04-11 17:22 UTC, alick commented on _posts/2018-04-03-modularity-dead-long-live-modularity.md
> +藉此设计，**对于模块提供的附加软件版本没有需求的人，可以禁用 modular 和 modular-updates 这两个仓库，其系统的功能也会安然无恙**。使用 Fedora 传统程序构建的软件包将通过常规 Fedora 软件仓库安装和管理，而默认版本的软件包则将在后台使用新的进程。
借此设计

2018-04-11 17:23 UTC, alick requested changes
看起来挺好的，感谢 Pany！我只有一个字的更正。

2018-04-12 00:38 UTC, geekpany commented
@alick 藉-->借 ，已经改过来了。感谢帮忙检查

2018-04-12 03:00 UTC, alick approved these changes

2018-04-12 03:01 UTC, merged