add use-ssl-vpn-in-fedora.md
FZUG/fzug.github.io pull request #20
Opened 2018-04-16 11:38 UTC by chinesejar

2018-04-16 17:24 UTC, alick commented on _posts/2018-04-16-use-ssl-vpn-in-fedora.md
> +
不要局限于一家公司。用 SSL VPN 的肯定不只一家。

2018-04-16 17:25 UTC, alick commented on _posts/2018-04-16-use-ssl-vpn-in-fedora.md
> +Mozilla 提供 Firefox 的 ESR(Extended Support Release) 版本给需要扩展支持的用户。目前最新的 32 位的 Firefox 52 ESR 还在继续支持 Java 运行插件。
ESR 和括号间加空格

2018-04-16 17:25 UTC, alick commented on _posts/2018-04-16-use-ssl-vpn-in-fedora.md
> +Mozilla 提供 Firefox 的 ESR(Extended Support Release) 版本给需要扩展支持的用户。目前最新的 32 位的 Firefox 52 ESR 还在继续支持 Java 运行插件。
64 位的就不行了吗？

2018-04-16 18:52 UTC, alick commented on _posts/2018-04-16-use-ssl-vpn-in-fedora.md
> +
看完后文，感觉这个教程可能只适用于这一家公司……所以标题改成“……使用 Sangfor 公司提供的 SSL VPN 解决方案”也许更好。

同时，我觉得需要一个免责声明。我们只是提供一个解决方案，无法为他们的 SSL VPN 服务负责，更不是推广宣传其服务。

2018-04-16 18:52 UTC, alick requested changes
有些意见建议

2018-04-16 22:58 UTC, chinesejar commented on _posts/2018-04-16-use-ssl-vpn-in-fedora.md
> +
谢谢你的建议，已经再次修改

2018-04-16 22:59 UTC, chinesejar commented on _posts/2018-04-16-use-ssl-vpn-in-fedora.md
> +Mozilla 提供 Firefox 的 ESR(Extended Support Release) 版本给需要扩展支持的用户。目前最新的 32 位的 Firefox 52 ESR 还在继续支持 Java 运行插件。
修改了，添加 java 官方说明的不支持 Firefox 的链接

2018-04-17 01:39 UTC, alick commented on _posts/2018-04-16-use-ssl-vpn-in-fedora.md
> +
了解了。不过不需要贴出大段的英文，附上其链接就好。

2018-04-17 04:35 UTC, chinesejar commented on _posts/2018-04-16-use-ssl-vpn-in-fedora.md
> +
恩恩

2018-04-17 17:21 UTC, alick commented on _posts/2018-04-16-use-ssl-vpn-in-fedora.md
> +详情参考 [Java 针对不支持 Firefox 帮助说明的内容](https://java.com/en/download/help/firefox_java.xml)
这句放到第16行段尾才通顺。记得加句末句号。

2018-04-17 17:23 UTC, alick commented on _posts/2018-04-16-use-ssl-vpn-in-fedora.md
> +以上输出提示缺少 `dbus-glib-0.110-2.fc28.i686` 这个依赖库
这里假定了用户在用 Fedora 28。更好的办法是 `sudo dnf install /usr/lib/libdbus-glib-1.so.2`。请调整相关语句。

2018-04-17 17:24 UTC, alick requested changes
上次遗漏了一点问题

2018-04-18 03:58 UTC, chinesejar commented on _posts/2018-04-16-use-ssl-vpn-in-fedora.md
> +以上输出提示缺少 `dbus-glib-0.110-2.fc28.i686` 这个依赖库
OK，学到了！

2018-04-18 16:27 UTC, alick approved these changes

2018-04-18 16:27 UTC, merged