添加新文章「Fedora 忘记 root 密码怎么办？」
FZUG/fzug.github.io pull request #21
Opened 2018-04-26 07:54 UTC by geekpany

Signed-off-by: Pany <pany@fedoraproject.org>

2018-04-26 16:59 UTC, alick commented on _posts/2018-04-26-reset-root-password-fedora.md
> +**注：**之所以设置 `enforcing=0` 是为了避免 SELinux 造成干扰。等到系统重启后，需要恢复 `/etc/shadow` 文件的 SELinux <ruby>上下文<rt>context</rt></ruby>标签（下方中会解释）。
这种 <ruby> 的用法我是头一次看到。我觉得并不比行内括号加注好。
下方中会解释->下方会有解释

2018-04-26 17:00 UTC, alick commented on _posts/2018-04-26-reset-root-password-fedora.md
> +# mount –o remount,rw /sysroot
这个o前面的-不对，变成dash了

2018-04-26 17:00 UTC, alick commented on _posts/2018-04-26-reset-root-password-fedora.md
> +*系统现在会进入<ruby>紧急模式<rt>emergency mode</rt></ruby>。*现在需要重新挂载硬盘允许读写：
这个 `*` 格式好像不起效

2018-04-26 17:01 UTC, alick commented on _posts/2018-04-26-reset-root-password-fedora.md
> +重新将 SELinux 设置成<ruby>强制模式<rt>enforcing mode</rt></ruby>：
强制模式？启用模式？

2018-04-26 17:01 UTC, alick commented on _posts/2018-04-26-reset-root-password-fedora.md
> +以上。
?

2018-04-26 17:01 UTC, alick requested changes
小改

2018-04-26 22:42 UTC, geekpany commented on _posts/2018-04-26-reset-root-password-fedora.md
> +**注：**之所以设置 `enforcing=0` 是为了避免 SELinux 造成干扰。等到系统重启后，需要恢复 `/etc/shadow` 文件的 SELinux <ruby>上下文<rt>context</rt></ruby>标签（下方中会解释）。
「下文」打成「下方」了……

2018-04-26 22:51 UTC, geekpany commented on _posts/2018-04-26-reset-root-password-fedora.md
> +# mount –o remount,rw /sysroot
哇！历害历害！我从原文复制过来竟然没发现……

2018-04-26 23:07 UTC, geekpany commented on _posts/2018-04-26-reset-root-password-fedora.md
> +*系统现在会进入<ruby>紧急模式<rt>emergency mode</rt></ruby>。*现在需要重新挂载硬盘允许读写：
这里是想产生斜体的效果，应该是已经生效了。

在这种模式下看，行首那里被 GitHub 自动加了一个空格，但是如果你看 RAW 文件是没有的。

2018-04-26 23:08 UTC, geekpany commented on _posts/2018-04-26-reset-root-password-fedora.md
> +重新将 SELinux 设置成<ruby>强制模式<rt>enforcing mode</rt></ruby>：
已修改成「启用模式」

2018-04-26 23:10 UTC, geekpany commented on _posts/2018-04-26-reset-root-password-fedora.md
> +以上。
删掉了

2018-04-26 23:10 UTC, geekpany commented
已经修改了

2018-04-27 04:06 UTC, alick approved these changes

2018-04-27 04:07 UTC, merged