添加新文章「Fedora 28 Server 版中的模块化 (Modularity) 新特性」
FZUG/fzug.github.io pull request #24
Opened 2018-05-10 12:47 UTC by geekpany

Signed-off-by: Pany <pany@fedoraproject.org>

2018-05-10 19:36 UTC, alick commented on _posts/2018-05-10-Modularity-in-Fedora-28-Server-Edition.md
> +这是另一个常见的问题。当用户明明可以只用容器的时候，他们为什么还需要模块？答案是，仍然有些人必须在容器中维护软件。模块可以为那些不需要用户自己维护、更新和修补的容器提供预打包内容 (pre-packaged content)。Fedora 正是这样，将传统发行版的价值转移到了新的、容器化的世界之中。
- “只用”不合适，just use 这里是“用……就好”的意思。
- 仍然有些人必须在容器中维护软件：使用容器时需要用户在容器中维护（相应版本的）软件。
- 模块可以为那些不需要用户自己维护、更新和修补的容器提供预打包内容：模块可以为这些容器提供已经打包好的内容（软件），这样用户就不用自己维护、更新、以及打补丁了。
- 转移到了：带到、引入

2018-05-10 19:52 UTC, alick requested changes
小改

2018-05-11 00:04 UTC, geekpany commented
改好了，谢谢 @alick 的审校。

2018-05-11 02:09 UTC, alick approved these changes

2018-05-11 02:10 UTC, merged