update about page, fixed issues #22 and #23
FZUG/fzug.github.io pull request #25
Opened 2018-05-11 03:54 UTC by geekpany

Signed-off-by: Pany <pany@fedoraproject.org>

2018-05-12 01:58 UTC, alick commented on about.md
> +- 更多信息，请参阅 <https://fedoraproject.org/wiki/Zh/zh-cn>
更多信息：维基

2018-05-12 02:00 UTC, alick commented on about.md
> +- GitHub：本项目的页面 <https://github.com/FZUG/fzug.github.io>
我建议分“关于 FZUG”和“关于本网站”

2018-05-12 02:00 UTC, alick requested changes
小改

2018-05-13 05:10 UTC, geekpany commented
改过了， @alick 麻烦再看一下吧。

2018-05-13 15:42 UTC, alick commented on about.md
> +本项目在 GitHub 上的页面：<https://github.com/FZUG/fzug.github.io>
“本网站的源码”更清楚点

2018-05-13 15:43 UTC, alick requested changes
小改

2018-05-14 00:03 UTC, geekpany commented on about.md
> +本项目在 GitHub 上的页面：<https://github.com/FZUG/fzug.github.io>
已修改

2018-05-14 00:03 UTC, geekpany commented
已修改

2018-05-14 00:29 UTC, alick approved these changes

2018-05-14 00:29 UTC, merged