添加新文章「树莓派 3B+ 上使用 Fedora 28 连接 Wi-Fi」
FZUG/fzug.github.io pull request #33
Opened 2018-06-18 10:05 UTC by geekpany

Signed-off-by: Pany <pany@fedoraproject.org>

2018-06-18 10:11 UTC, sztsian commented on _posts/2018-06-18-fedora-28-on-raspberry-pi-3b-plus.md
> +title: 树莓派 3B+ 上使用 Fedora 28 连接 Wi-Fi
标题与原文差距太大。建议 “在树莓派 3B+ 上使用 Fedora 28”

2018-06-18 10:14 UTC, sztsian requested changes

2018-06-18 10:14 UTC, sztsian commented on _posts/2018-06-18-fedora-28-on-raspberry-pi-3b-plus.md
> +title: 树莓派 3B+ 上使用 Fedora 28 连接 Wi-Fi
标题与原文差距太大。建议 “在树莓派 3B+ 上使用 Fedora 28”

2018-06-18 10:30 UTC, geekpany commented on _posts/2018-06-18-fedora-28-on-raspberry-pi-3b-plus.md
> +title: 树莓派 3B+ 上使用 Fedora 28 连接 Wi-Fi
我是这样考虑的：
1. 文章确实主要讲的是如何连接（或者启用） Wi-Fi
    > This article will show you how to get wifi running on the RPi 3 B+.
2. 在标题是写明 Wi-Fi 字样会对 SEO 更有利（也许）

如果标题确实不妥的话我就改一下。

2018-06-19 01:26 UTC, sztsian commented on _posts/2018-06-18-fedora-28-on-raspberry-pi-3b-plus.md
> +title: 树莓派 3B+ 上使用 Fedora 28 连接 Wi-Fi
我是觉得这篇文章直观感觉是在讲如何安装 Fedora 到 RPI 3 .Wi-Fi 确实是其中很重要的部分，但 Wi-Fi 并不是本文的全部。所以我更倾向于忠于原文标题

2018-06-19 05:16 UTC, geekpany commented on _posts/2018-06-18-fedora-28-on-raspberry-pi-3b-plus.md
> +title: 树莓派 3B+ 上使用 Fedora 28 连接 Wi-Fi
改好了～

2018-06-25 03:06 UTC, merged