添加新文章「轻松上手 Python 调试器」
FZUG/fzug.github.io pull request #37
Opened 2018-07-30 14:56 UTC by geekpany

Signed-off-by: Pany <pany@fedoraproject.org>

2018-07-30 15:06 UTC, geekpany commented on _posts/2018-07-30-getting-started-python-debugger.md
> +Python 生态中包含了丰富的工具和库，可以极大地改善开发体验。例如，我们之前已经介绍了如何[使用交互式 shell 来改善 Python 编程体验](https://fedoramagazine.org/enhance-python-interactive-shell)。本文重点介绍另一种可以节省时间并提高 Python 技能的工具：Python 调试器。
等 #36 合并之后，我会把这里的链接换成 `{% post_url 2018-07-29-enhance-python-interactive-shell %}`

2018-08-01 06:12 UTC, alick commented on _posts/2018-07-30-getting-started-python-debugger.md
> +脚本会在断点处停止，*pdb* 会显示脚本中的下一行。你也可以在失败后执行调试器。这种方式又名：*事后* 调试（postmortem debugging）。
删掉冒号。

2018-08-01 06:14 UTC, alick commented on _posts/2018-07-30-getting-started-python-debugger.md
> +一些增强型调试器可提供更好的用户体验。大部分都为 *pdb* 添加了有用的额外功能，例如语法高亮显示、更好的回溯以及内省等。增强型调试器的常用选择有 [IPython 的 ipdb](https://github.com/gotcha/ipdb) 和 [pdb++](https://github.com/antocuni/pdb)。
解释下“内省”吧

2018-08-01 06:14 UTC, alick requested changes
少许意见

2018-08-01 08:06 UTC, geekpany commented
已修改

2018-08-10 04:47 UTC, sztsian commented
Over a week without objections. Merging.

2018-08-10 04:47 UTC, merged