添加新文章「使用 mypy 来改善你的 Python 项目」
FZUG/fzug.github.io pull request #38
Opened 2018-08-01 04:48 UTC by geekpany

Signed-off-by: Pany <pany@fedoraproject.org>

2018-08-01 06:04 UTC, alick commented on _posts/2018-07-31-improve-python-projects-mypy.md
> +    def __init__(self,surname,firstname,age,job):
原文里面参数之间没有空格吗？不一定能过 PEP8 检查吧。

2018-08-01 06:06 UTC, alick commented on _posts/2018-07-31-improve-python-projects-mypy.md
> +程序中还有其他错误。各位读者可以试着从中找找看。可以针对 `Person` 这个类使用类型提示。先自己尝试一下。想要检查一下的话，可以在 [Github](https://github.com/cverna/testing_mypy) 上参考这个没有错误的程序。
GitHub H 大写

2018-08-01 06:07 UTC, alick commented on _posts/2018-07-31-improve-python-projects-mypy.md
> +希望本篇 *mypy* 简短介绍可以对你的代码库有所禆益。 *mypy* 让我们可以更轻松地维护代码以及阅读应用程序代码。还可以让我们在代码运行之前发现错别字和错误。需要注意的是，*mypy* 也可用于 Python 2.7 应用程序。只不过，它在注释方面的语法会有不同。
需要注意的是：值得一提的是？

2018-08-01 06:07 UTC, alick requested changes
小改

2018-08-01 08:55 UTC, geekpany commented on _posts/2018-07-31-improve-python-projects-mypy.md
> +    def __init__(self,surname,firstname,age,job):
不好意思，疏忽了，是从原文复制的，确实有几处不符合 PEP8 的地方

2018-08-01 08:55 UTC, geekpany commented
已提交修改

2018-08-01 21:34 UTC, alick commented on new.py
> +            print(f'{person.surname} {person.firstname}')
这个文件正文有用到吗？

2018-08-01 21:36 UTC, alick requested changes
有个问题

2018-08-02 04:29 UTC, geekpany commented
已修改～

2018-08-10 04:49 UTC, sztsian commented
Over one week without objections. Merging.

2018-08-10 04:49 UTC, merged