添加新文章「在 Fedora 上写 Python 不妨试试 VS Code」
FZUG/fzug.github.io pull request #39
Opened 2018-08-03 04:44 UTC by geekpany

Signed-off-by: Pany <pany@fedoraproject.org>

2018-08-03 06:11 UTC, alick commented on _posts/2018-08-02-vscode-python-howto.md
> +如果你还没有安装 VS Code，可以参考 Fedora Magazine 上的这篇文章 [Using Visual Studio Code on Fedora](https://fedoramagazine.org/using-visual-studio-code-fedora/)。
这个引文翻译了吗？

2018-08-03 06:12 UTC, alick requested changes
有个疑问

2018-08-03 08:25 UTC, geekpany commented on _posts/2018-08-02-vscode-python-howto.md
> +如果你还没有安装 VS Code，可以参考 Fedora Magazine 上的这篇文章 [Using Visual Studio Code on Fedora](https://fedoramagazine.org/using-visual-studio-code-fedora/)。
引文没有翻译

2018-08-03 17:09 UTC, alick commented
建议译者注一下安装方式，这样读者不用再去看英文原文了

Regards,


On Fri, Aug 3, 2018 at 1:25 AM Pany <notifications@github.com> wrote:

> *@geekpany* commented on this pull request.
> ------------------------------
>
> In _posts/2018-08-02-vscode-python-howto.md
> <https://github.com/FZUG/fzug.github.io/pull/39#discussion_r207474929>:
>
> > @@ -0,0 +1,142 @@
> +---
> +layout: post
> +title: 在 Fedora 上写 Python 不妨试试 VS Code
> +date: 2018-08-02 12:38:14 +0800
> +categories: python
> +---
> +
> +> 本文翻译自 Clément Verna 的文章 [How to use VS Code for your Python projects](https://fedoramagazine.org/vscode-python-howto/)。
> +
> +Visual Studio Code 或者叫 VS Code 是一款开源的代码编辑器，同时它还包含了可以用于构建和调试应用程序的工具。启用 Python 扩展后，*VS Code* 便可成为各位 Python 开发人员舒适的工作环境。本文会向大家展示一下都有哪些实用扩展，以及如何配置 VS Code 来充分利用这些扩展。
> +
> +如果你还没有安装 VS Code，可以参考 Fedora Magazine 上的这篇文章 [Using Visual Studio Code on Fedora](https://fedoramagazine.org/using-visual-studio-code-fedora/)。
>
> 引文没有翻译
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/FZUG/fzug.github.io/pull/39#discussion_r207474929>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AA5AL4DXlLycl1uag9IdOhm3jBhu0m1Wks5uNAkAgaJpZM4VtXp4>
> .
>

2018-08-05 09:55 UTC, geekpany commented
安装方式加好了，@alick 麻烦看一下吧

2018-08-06 04:23 UTC, alick commented on _posts/2018-08-02-vscode-python-howto.md
> +  ```
删掉 yum 相关命令。对应 Fedora 版本太旧了

2018-08-06 04:23 UTC, alick requested changes
请修改

2018-08-06 06:36 UTC, geekpany commented
已修改～

2018-08-10 04:51 UTC, sztsian commented on _posts/2018-08-02-vscode-python-howto.md
> +- 添加 VS Code 64 位稳定版 yum 软件仓库
“yum 软件仓库” 能否改为 “软件仓库”？ 现在的安装器是 DNF 了。

2018-08-10 04:54 UTC, sztsian commented on _posts/2018-08-02-vscode-python-howto.md
> +> 本文翻译自 Clément Verna 的文章 [How to use VS Code for your Python projects](https://fedoramagazine.org/vscode-python-howto/)。
建议首部声明一下 VS Code 不在 Fedora 官方仓库，需要添加第三方仓库。

2018-08-10 05:10 UTC, geekpany commented on _posts/2018-08-02-vscode-python-howto.md
> +> 本文翻译自 Clément Verna 的文章 [How to use VS Code for your Python projects](https://fedoramagazine.org/vscode-python-howto/)。
加好了

2018-08-10 05:10 UTC, geekpany commented
已修改

2018-08-12 09:01 UTC, sztsian approved these changes
LGTM.  如果长时间没有其他意见你自己合并就好。

2018-08-13 08:52 UTC, merged