add protect-fedora-system-meltdown
FZUG/fzug.github.io pull request #4
Opened 2018-01-18 04:19 UTC by RobberPhex

2018-01-18 04:48 UTC, alick commented on _posts/2018-01-18-protect-fedora-system-meltdown.md
> +title:  "保护你的Fedora系统，防止Meltdown漏洞"
“防范”更好些

2018-01-18 04:49 UTC, alick commented on _posts/2018-01-18-protect-fedora-system-meltdown.md
> +title:  "保护你的Fedora系统，防止Meltdown漏洞"
meltdown 已经有官方翻译了：熔断
http://www.12377.cn/txt/2018-01/17/content_40190355.htm

2018-01-18 04:50 UTC, alick commented on _posts/2018-01-18-protect-fedora-system-meltdown.md
> +title:  "保护你的Fedora系统，防止Meltdown漏洞"
中英文之间加个空格更美观

2018-01-18 04:52 UTC, alick requested changes
有些修改意见

2018-01-18 05:59 UTC, RobberPhex commented
@alick 已经修改，再看看有什么问题吗

2018-01-18 17:54 UTC, alick commented on _posts/2018-01-18-protect-fedora-system-meltdown.md
> +## 关于Spectre的提示
“幽灵” (Spectre) 漏洞

2018-01-18 17:56 UTC, alick reviewed
另外一点，出于美观，括号里如果全英文，用半角括号。否则用全角括号。

2018-01-24 03:20 UTC, RobberPhex commented
@alick  updated

2018-01-24 12:39 UTC, sztsian commented on _posts/2018-01-18-protect-fedora-system-meltdown.md
> +新的内核包包含 Fedora 26 和 27 的补丁（内核版本4.14.11），以及Fedora Rawhide的布丁（内核4.15发布候选版本）。
Fedora Rawhide 两端的空格

2018-01-24 12:39 UTC, sztsian commented on _posts/2018-01-18-protect-fedora-system-meltdown.md
> +你或许已经听过 “熔断”(Meltdown) 漏洞，这是[一种可以用来攻击现代处理器](https://meltdownattack.com/) (CPU) 的漏洞，它可以恶意地访问内存中的敏感数据。
（CPU）最好与处理器位于同样位置（例如全在超链接里，或者全在超链接外）

2018-01-24 12:40 UTC, sztsian reviewed
添加了一些建议

2018-01-24 12:40 UTC, sztsian commented on _posts/2018-01-18-protect-fedora-system-meltdown.md
> +Fedora团队将继续跟进他们的进展，并在补丁可用时通知公众更新。
Fedora 后的空格

2018-01-25 00:18 UTC, RobberPhex commented
@alick 最后提到的几点，已经修改。

2018-01-25 01:48 UTC, sztsian requested changes

2018-01-25 01:48 UTC, sztsian commented on _posts/2018-01-18-protect-fedora-system-meltdown.md
> +新的内核包包含 Fedora 26 和 27 的补丁（内核版本4.14.11），以及 Fedora Rawhide 的布丁（内核4.15发布候选版本）。
"布丁"

2018-01-25 01:49 UTC, sztsian commented
呃，又找到一个错别字 xD

2018-01-25 02:16 UTC, RobberPhex commented on _posts/2018-01-18-protect-fedora-system-meltdown.md
> +新的内核包包含 Fedora 26 和 27 的补丁（内核版本4.14.11），以及 Fedora Rawhide 的布丁（内核4.15发布候选版本）。
fixed

2018-01-25 04:35 UTC, sztsian approved these changes
LGTM

2018-01-25 04:36 UTC, merged

2018-01-25 04:36 UTC, sztsian commented
我直接Merge了。