加入文章：保护数据，用 LUKS 给磁盘全盘加密
FZUG/fzug.github.io pull request #43
Opened 2018-12-04 16:23 UTC by n0vad3v

分享最近的一個全盤加密的實驗，如果可能的話希望可以頂部署名並加入博客上文章地址：https://nova.moe/encrypt-disk-with-luks/ .

2018-12-04 16:54 UTC, alick commented on _posts/2018-12-05-encrypt-disk-with-luks.md
> +继第二块硬盘被 Oxxxo 硬盘盒给毁掉了之后，最近入手了块新的移动硬盘用于备份数据，到手之后第一件事情是对硬盘进行加密，之前经常使用的 VeraCrypt，由于这块硬盘不需要在其他平台上使用，所以这次打算换点玩法，充分利用上系统自带的 LUKS，来完成对设备的加密.
这一段的口吻不像是 turorial 教程，更像是博客日志

2018-12-04 16:59 UTC, alick commented on _posts/2018-12-05-encrypt-disk-with-luks.md
> +如果你的设备和你在同一个区域/国家的话，加密你的设备**只能防止因为设备失窃带来的信息泄漏或者让你知道你的设备正在被第三方尝试获取（比如在你睡着的时候偷走设备进行取证）**，真正隐私的信息还是尽量做到隐藏或者放在一个对你没有司法管理权的区域，毕竟再好的加密，也没法抵抗一根 5 美元不到的棍子，人的因素，永远是信息安全中最弱的一环.
隐私的问题值得提及，但这里有点戏谑。另外，假如数据存放在 A 国，A 国确实可能找不到你本人，但是 A 国对在 A 国储存数据的公司是有司法管辖权的，所以这里的建议并不一定可取。

2018-12-04 17:00 UTC, alick requested changes
一些小建议

2018-12-04 17:03 UTC, alick commented
另外，署名和原始链接加入没有问题，而且鼓励加入。格式请参考 https://github.com/FZUG/fzug.github.io/commit/3ac5ed2cd11f0acc568563ed9a5a836b1963450e （转载声明可以放在正文前）

2018-12-05 01:10 UTC, n0vad3v commented on _posts/2018-12-05-encrypt-disk-with-luks.md
> +继第二块硬盘被 Oxxxo 硬盘盒给毁掉了之后，最近入手了块新的移动硬盘用于备份数据，到手之后第一件事情是对硬盘进行加密，之前经常使用的 VeraCrypt，由于这块硬盘不需要在其他平台上使用，所以这次打算换点玩法，充分利用上系统自带的 LUKS，来完成对设备的加密.
唔，已經刪除.

2018-12-05 01:11 UTC, n0vad3v commented on _posts/2018-12-05-encrypt-disk-with-luks.md
> +如果你的设备和你在同一个区域/国家的话，加密你的设备**只能防止因为设备失窃带来的信息泄漏或者让你知道你的设备正在被第三方尝试获取（比如在你睡着的时候偷走设备进行取证）**，真正隐私的信息还是尽量做到隐藏或者放在一个对你没有司法管理权的区域，毕竟再好的加密，也没法抵抗一根 5 美元不到的棍子，人的因素，永远是信息安全中最弱的一环.
主要是這樣考慮的，如果你所在的 B 國，並且將數據存儲到了 A 國，那麼 A 國並不一定會理會 B 國發來的要求獲取數據的請求，這樣雖然 A 國對數據具有管轄權（比如可以向 A 國法院交出數據），但是並不會因此導致 B 國對個人帶來影響.
不過消除歧義考慮我已經將這一段刪除.

2018-12-05 01:49 UTC, alick approved these changes

2018-12-05 01:50 UTC, merged

2018-12-05 01:50 UTC, alick commented
感谢投稿！

2018-12-06 12:42 UTC, sztsian commented
啊感谢！
有了这篇我就可以直接写 Celvis/Tang 而不用再描述 luks 了