Add the release note of Fedora 30
FZUG/fzug.github.io pull request #50
Opened 2019-05-03 02:57 UTC by bootingman

Add the release note of Fedora 30, Chinese version.

2019-05-03 03:52 UTC, alick requested changes
稍微改下吧，谢谢！

2019-05-03 03:52 UTC, alick commented on _posts/2019-05-01-fedora-30-released.md
> +
edition 前面翻译了后面没有。这个确实也难翻译，中文很难和 release 的“版本”分开。我建议模糊处理。比如 “Fedora 针对不同应用场景提供了诸多版本”，“除了上述以外”。小节标题里的 Variants 中文也是“版本”……“变体”不太好听，我建议意译成“众多面孔”

2019-05-03 03:52 UTC, alick commented on _posts/2019-05-01-fedora-30-released.md
> +Fedora 是一个由 Red Hat 赞助、Fedora 项目社区支持的独立 Linux 发行版。其提供了开箱即用的用户体验，默认搭载 GNOME 桌面环境。
Red Hat -> 红帽公司

2019-05-03 03:52 UTC, alick commented on _posts/2019-05-01-fedora-30-released.md
> +此外，随着 Fedora 30 的版本的发布，该项目正在将「[Ask Fedora](http://ask.fedoraproject.org/)」支持论坛迁移至基于 Discourse 的新平台。这一新的论坛非常简明，且为包含[简体中文](https://ask.fedoraproject.org/c/Simplified-Chinese)在内的诸多非英语语言设有独立板块。
“该项目”不妥，因为这是 Fedora 社区。改为“我们”

2019-05-03 03:52 UTC, alick commented on _posts/2019-05-01-fedora-30-released.md
> +Fedora 在中文社区比较知名，安装与使用门槛低，适合新手。提供了三个版本：适合个人用户的 Workstation、用于服务器的 Server 及关注于容器技术的 Atomic 版。其 Workstation 版本默认配置 GNOME 桌面环境（自 F25 起，默认使用 Wayland），但通过 Fedora 独有的 <a href="https://spins.fedoraproject.o
从上个 --- 到这里应该删掉。

2019-05-03 10:30 UTC, geekpany requested changes
一点小细节，麻烦修改一下吧

2019-05-03 10:30 UTC, geekpany commented on _posts/2019-05-01-fedora-30-released.md
> +
现在 <fedoraproject.org> 会自动跳转到 <getfedora.org> 了，所以我觉得上面两行可以合并成一个链接

2019-05-14 12:21 UTC, bootingman commented on _posts/2019-05-01-fedora-30-released.md
> +Fedora 是一个由 Red Hat 赞助、Fedora 项目社区支持的独立 Linux 发行版。其提供了开箱即用的用户体验，默认搭载 GNOME 桌面环境。
updated

2019-05-14 12:23 UTC, bootingman commented on _posts/2019-05-01-fedora-30-released.md
> +
"众多面孔”感觉也不太顺，我把第二个 "edtions" 和“变体”去掉了

2019-05-14 12:25 UTC, bootingman commented on _posts/2019-05-01-fedora-30-released.md
> +此外，随着 Fedora 30 的版本的发布，该项目正在将「[Ask Fedora](http://ask.fedoraproject.org/)」支持论坛迁移至基于 Discourse 的新平台。这一新的论坛非常简明，且为包含[简体中文](https://ask.fedoraproject.org/c/Simplified-Chinese)在内的诸多非英语语言设有独立板块。
“我们”是第一人称，不适合这种语境，我改成了“ 社区”

2019-05-14 12:27 UTC, bootingman commented on _posts/2019-05-01-fedora-30-released.md
> +Fedora 在中文社区比较知名，安装与使用门槛低，适合新手。提供了三个版本：适合个人用户的 Workstation、用于服务器的 Server 及关注于容器技术的 Atomic 版。其 Workstation 版本默认配置 GNOME 桌面环境（自 F25 起，默认使用 Wayland），但通过 Fedora 独有的 <a href="https://spins.fedoraproject.o
这段话对于熟悉 Fedora 的同学可能没有意义，但是对于不了解 Fedora 的同学有意义，中文社区网站受众应该是了解的，我接受删掉的建议。

2019-05-14 12:28 UTC, bootingman commented on _posts/2019-05-01-fedora-30-released.md
> +
ok,已删除下载链接

2019-05-14 15:49 UTC, alick approved these changes

2019-05-14 15:51 UTC, merged

2019-05-14 15:51 UTC, alick commented
Thanks @bootingman !