添加新文章「如何使用 virt-manager 来操控虚拟机」
FZUG/fzug.github.io pull request #52
Opened 2019-07-23 17:40 UTC by geekpany

Signed-off-by: Pany <pany@fedoraproject.org>

2019-07-23 22:34 UTC, alick commented on _posts/2019-07-23-full-virtualization-system-on-fedora-workstation-30.md
> +早先时候，如果想要在笔记本上多个系统的话，大家可能会选择做成多启动的模式。而其缺点就是没办法同时运行多个系统或者在多个系统之间进行互通。多年之后，这些都不再是问题了，即使在普通的个人电脑上，也可以通过虚拟化的方式在一个系统之中运行另外其他的系统。
- 如果想要在笔记本上**安装**多个系统的话
- 多启动？双/多系统吧

2019-07-23 22:35 UTC, alick requested changes
minor changes

2019-07-24 01:44 UTC, geekpany commented
@alick 改好了～

2019-07-24 01:56 UTC, alick approved these changes

2019-07-24 01:57 UTC, merged