添加新文章「在 Fedora 上入门 Jupyter 与数据科学」
FZUG/fzug.github.io pull request #54
Opened 2019-07-27 15:03 UTC by geekpany

Signed-off-by: Pany <pany@fedoraproject.org>

2019-07-27 15:06 UTC, sztsian commented on _posts/2019-07-03-jupyter-and-data-science-in-fedora.md
> +在过去，君主和领袖会依赖先知和巫师来预测未来——或者借助其神秘力量来探测潜在信息。现如今，我们生活在一个格物致知的世界之中。于是我们便有了数据科学来完成这些工作。
`格物致知` 我倾向于直译。。

2019-07-28 02:27 UTC, sztsian commented on _posts/2019-07-24-jupyter-and-data-science-in-fedora.md
> +在过去，君主和领袖会依赖先知和巫师来预测未来——或者借助其神秘力量来探测潜在信息。现如今，我们生活在一个格物致知的世界之中。于是我们便有了数据科学来完成这些工作。
`Nowadays, we live in a society obsessed with quantifying everything.`  建议直译。感觉 `格物致知` 在这儿虽然读起来很文雅，但不利于理解背景。

2019-07-28 02:29 UTC, sztsian commented on _posts/2019-07-24-jupyter-and-data-science-in-fedora.md
> +1. 哪套房子的价格高于或低于均价？对于某一套房，其合理的价格是多少？
`哪套房子的价格高于或低于均价？` 我觉得这儿不宜翻译为均价。 Fair price 理解为合理的价位更适合这个场景。例如 `哪套房子价格超出合理或者低于合理价位`

2019-07-28 02:32 UTC, sztsian commented on _posts/2019-07-24-jupyter-and-data-science-in-fedora.md
> +Jupyter 是一款可以完美适用于这些任务的 web 应用。Jupyter 可以搭配笔记本（Notebooks）、文档来使用，其中可以整合富文本，包括渲染精美的数学公式（得益于 [mathjax](http://mathjax.org) 的加持）、代码块、代码输出，甚至还包括输出的图像等。
Notebooks 作为专有名词，不翻译也许更好。

2019-07-28 02:35 UTC, sztsian commented on _posts/2019-07-24-jupyter-and-data-science-in-fedora.md
> +涉及到文件路径时，用户名的部分需要改成你自己的。密码那一串是当你创建密码时自动生成的。pem 相关的那一部分是 *sscg* 创建的加密相关的文件。
`用户名的部分` 建议直接写成 `/home/aviram 部分`，或者 `家目录的路径`。主要是有些场景（例如我的某些工作环境），我的家目录并不在 /home/zsun

2019-07-28 02:40 UTC, sztsian commented on _posts/2019-07-24-jupyter-and-data-science-in-fedora.md
> +![标准化之后的旅客量随时间变化趋势（蓝线）与 ARIMA 预测的旅客量（红线）](/assets/2019/07/24/time-series.png)
我们上学的时候 normalized 中文用的是 `归一化`。也许得看下 @alick 用的什么。

2019-07-28 02:43 UTC, sztsian commented on _posts/2019-07-24-jupyter-and-data-science-in-fedora.md
> +作为机器学习生态系统的核心部分，[scikit](https://scikit-learn.org/stable/) 为[回归](https://scikit-learn.org/stable/supervised_learning.html#supervised-learning)（弹性网、梯度提升、随机森林等）以及[分类](https://scikit-learn.org/stable/su
`提供了预测算法`  ->  `提供了算法`

2019-07-28 02:44 UTC, sztsian commented on _posts/2019-07-24-jupyter-and-data-science-in-fedora.md
> +[自然语言工具箱](https://www.nltk.org)，或者叫 NLTK，可以帮我们处理人类语言数据，从而实现构建聊天机器人等工具（只是举个例子）。
`从而实现构建聊天机器人等工具（只是举个例子）` -> `从而实现构建例如聊天机器人等工具`

2019-07-28 02:45 UTC, sztsian requested changes
一些建议。

2019-07-28 02:51 UTC, alick commented on _posts/2019-07-24-jupyter-and-data-science-in-fedora.md
> +*通过梯度下降算法搜索一个价值函数的最优值，用 matplotlib 绘制的一对图形*
cost function: 成本函数

2019-07-28 02:54 UTC, alick commented on _posts/2019-07-24-jupyter-and-data-science-in-fedora.md
> +机器学习算法非常擅长预测，但不善于解释他们为什么会得出该预测结果。[SHAP](https://github.com/slundberg/shap) 就是为了解决这个需求，方法就是分析训练的模型。
解决这个问题

2019-07-28 02:55 UTC, alick requested changes
小改

2019-07-28 03:00 UTC, alick commented
“归一化”是对的。


On Sat, Jul 27, 2019 at 9:40 PM Zamir SUN <notifications@github.com> wrote:

> *@sztsian* commented on this pull request.
> ------------------------------
>
> In _posts/2019-07-24-jupyter-and-data-science-in-fedora.md
> <https://github.com/FZUG/fzug.github.io/pull/54#discussion_r307983201>:
>
> > +
> +*通过梯度下降算法搜索一个价值函数的最优值，用 matplotlib 绘制的一对图形*
> +
> +### Seaborn
> +
> +Seaborn 基于 matplotlib 进行构建，其绘图是经过优化的，可以更好地统计数据。它会自动画出数据的回归线或高斯曲线近似值。
> +
> +![利用 SeaBorn 进行线性回归的可视化](/assets/2019/07/24/regression_marginals.png)
> +
> +*利用 SeaBorn 进行线性回归的可视化*
> +
> +### [StatsModels](https://www.statsmodels.org/)
> +
> +StatsModels 可以为统计和计量经济学数据分析提供算法，如线性和逻辑回归。Statsmodel 同样适用于 ARIMA 等经典[时间序列算法](https://www.statsmodels.org/stable/examples/index.html#stats)系列。
> +
> +![标准化之后的旅客量随时间变化趋势（蓝线）与 ARIMA 预测的旅客量（红线）](/assets/2019/07/24/time-series.png)
>
> 我们上学的时候 normalized 中文用的是 归一化。也许得看下 @alick <https://github.com/alick> 用的什么。
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/FZUG/fzug.github.io/pull/54?email_source=notifications&email_token=AAHEAL6K5QXJPQPBKW4IRULQBUBIJA5CNFSM4IHJTXP2YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOB7YYVDQ#pullrequestreview-267487886>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAHEAL7A5LM2VXZ2RSG2D5TQBUBIJANCNFSM4IHJTXPQ>
> .
>

2019-07-28 03:29 UTC, geekpany commented
都改好了～

2019-07-28 03:35 UTC, sztsian approved these changes

2019-07-28 03:44 UTC, merged