添加新文章「用 Bitwarden 和 Podman 打造个人密码管理器」
FZUG/fzug.github.io pull request #55
Opened 2019-07-29 16:28 UTC by geekpany

Signed-off-by: Pany <pany@fedoraproject.org>

2019-07-30 02:51 UTC, alick commented on _posts/2019-07-29-manage-your-passwords-with-bitwarden-and-podman.md
> +这三款应用都有各自的不足。Bitwarden 将所有东西存储在一个地方，并且会通过其 API 和网站界面暴露在网络上。LessPass 无法存储自定义密码，因为它是无状态的，所以你需要使用由它演算出来的密码。KeePass 是一款基于文件的密码管理器，所以在多设备之间同步就会有点麻烦。你可以通过 [WebDAV](https://en.wikipedia.org/wiki/WebDAV)将云存储
WebDav 链接后应有一个空格

2019-07-30 02:57 UTC, alick commented on _posts/2019-07-29-manage-your-passwords-with-bitwarden-and-podman.md
> +该命令会下载 bitwarden_rs 镜像，并在用户命名空间下的用户容器中运行它。它使用了一个大于 1024 的非特权端口，所以不需要 root 权限便可以绑定端口。另外，我们用 *:Z* 更改了卷的 SELinux 上下文，这样在 */date* 上读写时就可以避免权限问题。
date ->data

2019-07-30 02:58 UTC, alick commented on _posts/2019-07-29-manage-your-passwords-with-bitwarden-and-podman.md
> +现在就可以[用 ](https://fedoramagazine.org/howto-use-sudo/)*[sudo](https://fedoramagazine.org/howto-use-sudo/)* 来启动它了：
重复链接。

2019-07-30 02:59 UTC, alick commented on _posts/2019-07-29-manage-your-passwords-with-bitwarden-and-podman.md
> +生成证书之后，你可以依照[这里的步骤](https://github.com/dani-garcia/bitwarden_rs/wiki/Enabling-HTTPS)来为 bitwarden_rs 配置 HTTPS。不过请记得在 Let's Encrypt 卷的后面加上 *Z:* 来处理权限，而且不要修改端口哦。
Z: or :Z ? 和前面不一致。

2019-07-30 03:00 UTC, alick requested changes
请修改

2019-07-30 03:33 UTC, sztsian commented on _posts/2019-07-29-manage-your-passwords-with-bitwarden-and-podman.md
> +生成证书之后，你可以依照[这里的步骤](https://github.com/dani-garcia/bitwarden_rs/wiki/Enabling-HTTPS)来为 bitwarden_rs 配置 HTTPS。不过请记得在 Let's Encrypt 卷的后面加上 *Z:* 来处理权限，而且不要修改端口哦。
应该是 `:Z`

2019-07-30 03:38 UTC, sztsian commented on _posts/2019-07-29-manage-your-passwords-with-bitwarden-and-podman.md
> +```
这儿有个非翻译方面的问题。我感觉这 Systemd Service 与前述命令效果不同。也许可以试下之后加个译注。

2019-07-30 16:57 UTC, geekpany commented on _posts/2019-07-29-manage-your-passwords-with-bitwarden-and-podman.md
> +```
`podman run` -> `podman start`

对吗？

2019-08-01 14:36 UTC, sztsian commented on _posts/2019-07-29-manage-your-passwords-with-bitwarden-and-podman.md
> +```
这是一个方面。另一方面是这个 systemd service 似乎没定义 volume，所以数据可能不能持久化？我不太确定唉。你要么自己试下，要么就先乎略我的回复吧。

2019-08-04 13:25 UTC, geekpany commented on _posts/2019-07-29-manage-your-passwords-with-bitwarden-and-podman.md
> +```
@sztsian  我解释一下啊：
```
$ podman run -d \
 --userns=keep-id \
 --name bitwarden \
 -e SIGNUPS_ALLOWED=false \
 -e ROCKET_PORT=8080 \
 -v /home/egustavs/Bitwarden/bw-data/:/data/:Z \
 -p 8080:8080 \
 bitwardenrs/server:latest
```
这里的 `--name bitwarden ` 指定了这个 container 的名字叫 `bitwarden`，因而在之后的命令中，只需要 `podman start bitwarden` 就可以运行这个 container，不需要再把 `port`、`volume` 等指定一遍了。

因而，正确做法应该就是在 systemd service 里写 `ExecStart=/usr/bin/podman start 'bitwarden'`，而不是 `run`。只不过 service 里的 `User` 和 `Group` 这两行需要换成读者的用户名和组名，这里确实是需要加上译注提示的。

然而，比较尴尬的是，我测试用 podman 创建的这个容器自己会异常退出，原因我还需要找一下……

2019-08-05 10:30 UTC, geekpany commented on _posts/2019-07-29-manage-your-passwords-with-bitwarden-and-podman.md
> +```
找到解决方案了，`[Service]` 里加一行 `Type=forking` 就可以了

2019-08-05 10:34 UTC, geekpany commented
该修改的都已经修改好了，抱歉拖了这么久……

2019-08-05 16:15 UTC, alick approved these changes

2019-08-05 16:16 UTC, merged

2019-08-05 16:16 UTC, alick commented
@geekpany 如果英文原文里的 unit 文件不正确的话，你最好在原文下面评论下？

2019-08-06 02:29 UTC, geekpany commented
@alick 我在[邮件列表](https://lists.fedoraproject.org/archives/list/magazine@lists.fedoraproject.org/message/H4YBNJ6IM4O6ZU236LQVY6GSFKBK3KQ2/)里反馈了