add copyright statement
FZUG/fzug.github.io pull request #71
Opened 2021-06-13 15:47 UTC by geekpany

ref: #70

Signed-off-by: Pany <pany@fedoraproject.org>

2021-06-13 19:24 UTC, alick requested changes

2021-06-13 19:24 UTC, alick commented on copyright.md
> +> - 没有附加限制 — 您不得适用法律术语或者 技术措施 从而限制其他人做许可协议允许的事情。
适用->使用，
技术措施前后的多余空格

PS: 原文如此吗？

2021-06-13 19:24 UTC, alick commented
这个文件会在网页显示吗？

2021-06-14 14:59 UTC, geekpany commented
效果如图：

<img width="817" alt="Screen Shot 2021-06-14 at 10 56 44 PM" src="https://user-images.githubusercontent.com/34344425/121913598-1e144280-cd64-11eb-8650-8d18e6836270.png">

2021-06-14 15:04 UTC, geekpany commented on copyright.md
> +> - 没有附加限制 — 您不得适用法律术语或者 技术措施 从而限制其他人做许可协议允许的事情。
原文中的错别字我修改了，并且在括号里注明了「稍加修改」（符合 CC BY-SA 4.0）。确实，明确地表达意思比照搬原文更重要

2021-06-16 03:31 UTC, alick approved these changes

2021-06-16 03:31 UTC, merged