add 2023-02-03 显示/HDR 黑客节的公告
FZUG/fzug.github.io pull request #85
Opened 2023-02-03 16:04 UTC by Hanjingxue-Boling

从[文档站](https://whiteboard-ui8.pages.dev/)同步的一篇新闻稿。

- 源文：<https://whiteboard-ui8.pages.dev/translation/display-hdr-hackfest/>

2023-02-05 14:15 UTC, geekpany requested changes
建议稍作修改

2023-02-05 14:15 UTC, geekpany commented on _posts/2023-02-03-display-hdr-hackfest.md
> +本次黑客节的目的是汇集来自显示/GPU 堆栈的贡献者。与会者将包括来自 [Freedesktop](https://freedesktop.org)、[GNOME](https://www.gnome.org/)、[KDE](https://kde.org/)、[Mesa](https://mesa3d.org)、[Wayland](https://wayland.freedesktop.org
the display/GPU stack 译成「显示、GPU 技术栈」是不是更合适呢？

2023-02-05 14:15 UTC, geekpany commented on _posts/2023-02-03-display-hdr-hackfest.md
> +最后，支持 HDR 符合 [Fedora 的基础](https://docs.fedoraproject.org/en-US/project/)，我们希望做正确的事情，确保每个人都可以自由享受最新的创新和功能。在我们迁移到 Wayland 之后，Wayland 作为一个现代图形堆栈，允许我们构建这样的新功能。
「支持 HDR 符合 Fedora 的基础」这一句建议可以稍作意译：「支持 HDR 也更符合 Fedora 项目的原则」

2023-02-05 14:22 UTC, Hanjingxue-Boling commented on _posts/2023-02-03-display-hdr-hackfest.md
> +最后，支持 HDR 符合 [Fedora 的基础](https://docs.fedoraproject.org/en-US/project/)，我们希望做正确的事情，确保每个人都可以自由享受最新的创新和功能。在我们迁移到 Wayland 之后，Wayland 作为一个现代图形堆栈，允许我们构建这样的新功能。
「Fedora’s Mission and Foundations」一直没有完整的翻译，我在对比其他语种的译文时，没想出一个合适的译名。

2023-02-05 14:22 UTC, Hanjingxue-Boling commented on _posts/2023-02-03-display-hdr-hackfest.md
> +本次黑客节的目的是汇集来自显示/GPU 堆栈的贡献者。与会者将包括来自 [Freedesktop](https://freedesktop.org)、[GNOME](https://www.gnome.org/)、[KDE](https://kde.org/)、[Mesa](https://mesa3d.org)、[Wayland](https://wayland.freedesktop.org
确实如此

2023-02-05 14:26 UTC, geekpany approved these changes
我觉得 OK

2023-02-05 17:35 UTC, alick requested changes

2023-02-05 17:35 UTC, alick commented on _posts/2023-02-03-display-hdr-hackfest.md
> +
free 是自由，不是免费？

2023-02-05 17:35 UTC, alick commented on _posts/2023-02-03-display-hdr-hackfest.md
> +我是[红帽](https://en.wikipedia.org/wiki/Red_Hat) GPU 团队的工程经理 Carlos Soriano。我与红帽的主要 HDR 开发人员 Sebastian Wick 和红帽的 GPU 团队产品负责人 Niels de Graef 一起宣布我们将于 4 月 24 日至 26 日在[捷克共和国的布尔诺](https://en.wikipedia.org/w
primary HDR developer: 首席 HDR 开发人员？HDR 主要开发人员？

2023-02-05 17:35 UTC, alick commented on _posts/2023-02-03-display-hdr-hackfest.md
> +从技术角度来看，启用这些模式并呈现内容并不难，显示器只需显示单一来源即可。虽然这可能适用于某些用例，但通用桌面需要将各种[标准动态范围](https://en.wikipedia.org/wiki/Standard-dynamic-range_video) (SDR) 信号、色彩管理 SDR 信号和各种 HDR 信号同时组合到各种 SDR 显示器、色彩管理显示器和 HDR 显示器。如果你想看看正
只要显示器只需显示单一来源即可

2023-02-05 17:35 UTC, alick commented on _posts/2023-02-03-display-hdr-hackfest.md
> +目前还没有针对这种合成的行业标准，而且大多数 HDR 模式（不幸的是所有常见模式），也不是为这种用例设计的。相反，他们专注于呈现单个 HDR 源。
而且大多数 HDR 模式（很不幸所有常见模式）也

2023-02-05 17:35 UTC, alick commented on _posts/2023-02-03-display-hdr-hackfest.md
> +随着合成复杂性的增加，卸载合成和实现零拷贝直接扫描场景变得更加困难。但这也需要控制功耗，从而延长电池寿命。
卸载合成 -> 合成负载转移？

2023-02-05 17:35 UTC, alick commented on _posts/2023-02-03-display-hdr-hackfest.md
> +是的，这一切听起来比人们想象的要复杂得多，但我们相信我们能做到。现在，为什么 HDR 对我们很重要；一旦准备就绪，我们将其集成到 Fedora 中的计划是什么？Niels de Graef 在红帽已经作为主要的 HDR 功能负责人工作了几个月，可以帮助我们理解这一点。
为什么 HDR 对我们很重要？

2023-02-05 17:35 UTC, alick commented on _posts/2023-02-03-display-hdr-hackfest.md
> +是的，这一切听起来比人们想象的要复杂得多，但我们相信我们能做到。现在，为什么 HDR 对我们很重要；一旦准备就绪，我们将其集成到 Fedora 中的计划是什么？Niels de Graef 在红帽已经作为主要的 HDR 功能负责人工作了几个月，可以帮助我们理解这一点。
他可以帮助我们理解这一点

2023-02-05 17:35 UTC, alick commented on _posts/2023-02-03-display-hdr-hackfest.md
> +随着内容创作者的发展，一个重要的利益相关者是[视效](https://en.wikipedia.org/wiki/Visual_effects)行业，它由像迪士尼这样的大公司组成。红帽与视效业界密切合作，业界也[推荐](https://drive.google.com/file/d/12k-YZVHuxJs0LVKH_l6l9nf_qcYLfaLJ/view)使用 RHEL 作为他们的发行版选择
内容创作者不能用“发展”一词吧？内容创作者群体的发展？（原文确实不太清楚）

2023-02-05 17:35 UTC, alick commented on _posts/2023-02-03-display-hdr-hackfest.md
> +另一方面，我们希望为 Linux 用户赋能。支持 HDR 的硬件正变得越来越普遍，并且最近变得越来越便宜。HDR 得到越来越多的支持，越来越多的内容正在使用它。与 Windows 和 Mac 用户相比，只要我们没有 HDR 支持，Linux 用户的体验就会下降。
Linux 用户的体验就会相对较差

2023-02-05 17:35 UTC, alick commented on _posts/2023-02-03-display-hdr-hackfest.md
> +最后，支持 HDR 符合 [Fedora 项目的原则](https://docs.fedoraproject.org/en-US/project/)，我们希望做正确的事情，确保每个人都可以自由享受最新的创新和功能。在我们迁移到 Wayland 之后，Wayland 作为一个现代图形堆栈，允许我们构建这样的新功能。
我们已经迁移到了 Wayland，它作为……

2023-02-06 01:20 UTC, Hanjingxue-Boling commented on _posts/2023-02-03-display-hdr-hackfest.md
> +从技术角度来看，启用这些模式并呈现内容并不难，显示器只需显示单一来源即可。虽然这可能适用于某些用例，但通用桌面需要将各种[标准动态范围](https://en.wikipedia.org/wiki/Standard-dynamic-range_video) (SDR) 信号、色彩管理 SDR 信号和各种 HDR 信号同时组合到各种 SDR 显示器、色彩管理显示器和 HDR 显示器。如果你想看看正
源文直译得出的句子看着有些奇怪……

2023-02-06 01:30 UTC, Hanjingxue-Boling commented on _posts/2023-02-03-display-hdr-hackfest.md
> +我是[红帽](https://en.wikipedia.org/wiki/Red_Hat) GPU 团队的工程经理 Carlos Soriano。我与红帽的主要 HDR 开发人员 Sebastian Wick 和红帽的 GPU 团队产品负责人 Niels de Graef 一起宣布我们将于 4 月 24 日至 26 日在[捷克共和国的布尔诺](https://en.wikipedia.org/w
fixed

2023-02-06 01:30 UTC, Hanjingxue-Boling commented on _posts/2023-02-03-display-hdr-hackfest.md
> +目前还没有针对这种合成的行业标准，而且大多数 HDR 模式（不幸的是所有常见模式），也不是为这种用例设计的。相反，他们专注于呈现单个 HDR 源。
fixed

2023-02-06 01:30 UTC, Hanjingxue-Boling commented on _posts/2023-02-03-display-hdr-hackfest.md
> +随着合成复杂性的增加，卸载合成和实现零拷贝直接扫描场景变得更加困难。但这也需要控制功耗，从而延长电池寿命。
fixed

2023-02-06 01:30 UTC, Hanjingxue-Boling commented on _posts/2023-02-03-display-hdr-hackfest.md
> +是的，这一切听起来比人们想象的要复杂得多，但我们相信我们能做到。现在，为什么 HDR 对我们很重要；一旦准备就绪，我们将其集成到 Fedora 中的计划是什么？Niels de Graef 在红帽已经作为主要的 HDR 功能负责人工作了几个月，可以帮助我们理解这一点。
fixed

2023-02-06 01:31 UTC, Hanjingxue-Boling commented on _posts/2023-02-03-display-hdr-hackfest.md
> +随着内容创作者的发展，一个重要的利益相关者是[视效](https://en.wikipedia.org/wiki/Visual_effects)行业，它由像迪士尼这样的大公司组成。红帽与视效业界密切合作，业界也[推荐](https://drive.google.com/file/d/12k-YZVHuxJs0LVKH_l6l9nf_qcYLfaLJ/view)使用 RHEL 作为他们的发行版选择
我改成使用“汇聚”一词，应该与原本的 go 比较接近一些。

2023-02-06 01:31 UTC, Hanjingxue-Boling commented on _posts/2023-02-03-display-hdr-hackfest.md
> +另一方面，我们希望为 Linux 用户赋能。支持 HDR 的硬件正变得越来越普遍，并且最近变得越来越便宜。HDR 得到越来越多的支持，越来越多的内容正在使用它。与 Windows 和 Mac 用户相比，只要我们没有 HDR 支持，Linux 用户的体验就会下降。
fixed

2023-02-06 01:31 UTC, Hanjingxue-Boling commented on _posts/2023-02-03-display-hdr-hackfest.md
> +最后，支持 HDR 符合 [Fedora 项目的原则](https://docs.fedoraproject.org/en-US/project/)，我们希望做正确的事情，确保每个人都可以自由享受最新的创新和功能。在我们迁移到 Wayland 之后，Wayland 作为一个现代图形堆栈，允许我们构建这样的新功能。
fixed

2023-02-06 01:32 UTC, Hanjingxue-Boling commented on _posts/2023-02-03-display-hdr-hackfest.md
> +
fixed

2023-02-16 04:43 UTC, alick commented on _posts/2023-02-03-display-hdr-hackfest.md
> +从技术角度来看，启用这些模式并呈现内容并不难，显示器只需显示单一来源即可。虽然这可能适用于某些用例，但通用桌面需要将各种[标准动态范围](https://en.wikipedia.org/wiki/Standard-dynamic-range_video) (SDR) 信号、色彩管理 SDR 信号和各种 HDR 信号同时组合到各种 SDR 显示器、色彩管理显示器和 HDR 显示器。如果你想看看正
我感觉现在的版本改变了句意。原文应该是说在对显示器要求不高时，实现并不难。现在的版本似乎在说，显示器可以挑选来源之一来实现。

2023-02-21 03:22 UTC, alick approved these changes

2023-02-21 03:23 UTC, merged