add 2023-03-15 Fedora 38 Beta 版已发布
FZUG/fzug.github.io pull request #86
Opened 2023-03-15 02:00 UTC by Hanjingxue-Boling

从[文档站](https://whiteboard-ui8.pages.dev/)同步[一篇新闻](https://whiteboard-ui8.pages.dev/translation/fedora38-beta-released/)。

2023-03-16 04:34 UTC, alick commented on _posts/2023-03-15-fedora38-beta-released.md
> +- [中国大陆镜像站列表](./../guide/misc/mirror-site.md)
这个链接的完整（带域名的）地址是什么？

2023-03-16 04:57 UTC, Hanjingxue-Boling commented on _posts/2023-03-15-fedora38-beta-released.md
> +- [中国大陆镜像站列表](./../guide/misc/mirror-site.md)
https://whiteboard-ui8.pages.dev/guide/misc/mirror-site/

2023-03-17 03:29 UTC, alick requested changes
一些小修改

2023-03-17 03:29 UTC, alick commented on _posts/2023-03-15-fedora38-beta-released.md
> +- [获取 Fedora Linux 38 Beta for ARM](https://arm.fedoraproject.org/prerelease)
for ARM 翻译下？”ARM 版本“

2023-03-17 03:29 UTC, alick commented on _posts/2023-03-15-fedora38-beta-released.md
> +如果你正在分析应用程序，你会喜欢现在内置在官方包中的帧指针。这使得 Fedora Linux 成为寻求提高 Linux 应用程序性能的开发人员的绝佳平台。
~~帧指针 是一个软件包名吗？是的话保留原文~~

2023-03-17 03:29 UTC, alick commented on _posts/2023-03-15-fedora38-beta-released.md
> +Beta 版本是代码完整的，与最终版本非常相似。如果你花时间下载并试用 Beta 版，你可以检查并确保对你来说重要的事务正常运行。你发现和报告的每个错误不仅能帮助你，还能改善全球数百万 Fedora Linux 用户的体验！我们可以一起让 Fedora 坚如磐石。我们有一种协调新功能并尽可能向上游推送修复的文化。你的反馈不仅改进了 Fedora Linux，而且改进了整个 Linux 生态系统和
改进了-->能改进

2023-03-17 03:29 UTC, alick commented on _posts/2023-03-15-fedora38-beta-released.md
> +有关 Fedora Linux 38 Beta 版新功能的更多详细信息，你可以查阅 [Fedora Linux 38 Change set](https://fedoraproject.org/wiki/Releases/38/ChangeSet)。它包含有关此版本随附的新软件包和改进的更多技术信息。
ChangeSet （不译），或者“变更清单”。（英文原文似乎有拼写错误）

2023-03-17 03:32 UTC, alick commented on _posts/2023-03-15-fedora38-beta-released.md
> +- [中国大陆镜像站列表](./../guide/misc/mirror-site.md)
建议加上“译者注”声明

2023-03-17 04:19 UTC, Hanjingxue-Boling commented on _posts/2023-03-15-fedora38-beta-released.md
> +- [获取 Fedora Linux 38 Beta for ARM](https://arm.fedoraproject.org/prerelease)
ok

2023-03-17 04:19 UTC, Hanjingxue-Boling commented on _posts/2023-03-15-fedora38-beta-released.md
> +Beta 版本是代码完整的，与最终版本非常相似。如果你花时间下载并试用 Beta 版，你可以检查并确保对你来说重要的事务正常运行。你发现和报告的每个错误不仅能帮助你，还能改善全球数百万 Fedora Linux 用户的体验！我们可以一起让 Fedora 坚如磐石。我们有一种协调新功能并尽可能向上游推送修复的文化。你的反馈不仅改进了 Fedora Linux，而且改进了整个 Linux 生态系统和
done

2023-03-17 04:19 UTC, Hanjingxue-Boling commented on _posts/2023-03-15-fedora38-beta-released.md
> +有关 Fedora Linux 38 Beta 版新功能的更多详细信息，你可以查阅 [Fedora Linux 38 Change set](https://fedoraproject.org/wiki/Releases/38/ChangeSet)。它包含有关此版本随附的新软件包和改进的更多技术信息。
done

2023-03-17 04:19 UTC, Hanjingxue-Boling commented on _posts/2023-03-15-fedora38-beta-released.md
> +如果你正在分析应用程序，你会喜欢现在内置在官方包中的帧指针。这使得 Fedora Linux 成为寻求提高 Linux 应用程序性能的开发人员的绝佳平台。
https://imbearchild.cyou/archives/2023/02/fedora-38-frame-pointer/

2023-03-18 16:31 UTC, alick commented on _posts/2023-03-15-fedora38-beta-released.md
> +- [中国大陆镜像站列表](./../guide/misc/mirror-site.md)
建议修改

2023-03-19 00:55 UTC, Hanjingxue-Boling commented on _posts/2023-03-15-fedora38-beta-released.md
> +- [中国大陆镜像站列表](./../guide/misc/mirror-site.md)
ok

2023-04-11 09:33 UTC, geekpany approved these changes

2023-04-11 16:57 UTC, closed without merging