add three new posts
FZUG/fzug.github.io pull request #88
Opened 2023-04-19 04:39 UTC by Hanjingxue-Boling

新增：

- [Fedora Linux 38 现已正式发布](https://whiteboard-ui8.pages.dev/translation/fedora38-released/)
- [Fedora Workstation 38 的新亮点](https://whiteboard-ui8.pages.dev/translation/fedora38-whatnew/)

补档 :

- [Fedora 38 Beta 版已发布](https://whiteboard-ui8.pages.dev/translation/fedora38-beta-released/)（[PR#86](https://github.com/FZUG/fzug.github.io/pull/86)）

---

注意预览一下文本渲染样式是否存在问题。

2023-04-20 00:24 UTC, alick commented on _posts/2023-03-15-fedora38-beta-released.md
> +---
这篇要不不加吧？正式版已经有了。

2023-04-20 00:54 UTC, alick requested changes

2023-04-20 00:54 UTC, alick commented on _posts/2023-04-19-fedora38-released.md
> +当然，我们生产的不仅仅是 Edition。[Fedora Spins][spin] 和 [Labs][lab] 面向各种受众和用例，包括为计算神经科学提供工具的 [Fedora Comp Neuro]，以及提供轻量级桌面环境的 [Fedora LXQt] 等桌面环境。而且，不要忘记我们的备用架构：[ARM AArch64、Power 和 S390x][alt]。
备用-> 替代

2023-04-20 00:54 UTC, alick commented on _posts/2023-04-19-fedora38-released.md
> +我们很高兴你能试用新版本！请转到 <https://fedoraproject.org/> 并立即下载。如果你已经在运行 Fedora Linux，请按照[简单的升级说明][upgrading]进行操作。有关 Fedora Linux 38 中新功能的更多信息，请参阅[发行说明]。
试用 -> 体验?

2023-04-20 00:54 UTC, alick commented on _posts/2023-04-19-fedora38-released.md
> +我们很高兴你能试用新版本！请转到 <https://fedoraproject.org/> 并立即下载。如果你已经在运行 Fedora Linux，请按照[简单的升级说明][upgrading]进行操作。有关 Fedora Linux 38 中新功能的更多信息，请参阅[发行说明]。
发行说明->发行注记。（记得以前都是这样翻译）

2023-04-20 00:54 UTC, alick commented on _posts/2023-04-19-fedora38-released.md
> +如果你遇到了问题，请访问我们的 [Ask Fedora] 用户支持论坛。这里有一个包括[常见问题]的类别。
这里包含一个……类别

2023-04-20 00:54 UTC, alick commented on _posts/2023-04-19-fedora38-released.md
> +如果你遇到了问题，请访问我们的 [Ask Fedora] 用户支持论坛。这里有一个包括[常见问题]的类别。
原文的  common  issues 只有英文的。译者加个 https://discussion.fedoraproject.org/tags/c/ask/non-english/85/chinese-simplified 中文相关的链接？

2023-04-20 00:54 UTC, alick commented on _posts/2023-04-19-fedora38-whatnew.md
> +大多数 GNOME 应用程序都是基于 GTK 4.10 构建的。这引入了一个改进的，带有图标视图和图像预览的文件选择器。
多余的逗号。或者“带有图标视图和图像预览的”后面加个逗号

2023-04-20 00:54 UTC, alick commented on _posts/2023-04-19-fedora38-whatnew.md
> +
“多亏了新的字幕”有点奇怪。不太清楚原文指的什么。可以不译。

2023-04-20 00:54 UTC, alick commented on _posts/2023-04-19-fedora38-whatnew.md
> +[设置]已经进行了一轮更新，重点是改善每个设置面板的体验。以下是一些显着的变化：
显著

2023-04-20 00:54 UTC, alick commented on _posts/2023-04-19-fedora38-whatnew.md
> +- 鼠标、触摸板以及辅助功能的重大的重新设计显着提高了可用性。
显著

2023-04-20 00:54 UTC, alick commented on _posts/2023-04-19-fedora38-whatnew.md
> +- 您现在可以通过二维码将您的 Wi-Fi 凭据共享到另一台设备。
“设备”，“声音”等专指特定控制面板选项。加个引号？

2023-04-20 00:54 UTC, alick commented on _posts/2023-04-19-fedora38-whatnew.md
> +- 您现在可以通过二维码将您的 Wi-Fi 凭据共享到另一台设备。
凭据：密码/证书

2023-04-20 00:54 UTC, alick commented on _posts/2023-04-19-fedora38-whatnew.md
> +## 第三方存储库
软件仓库

2023-04-20 00:54 UTC, alick commented on _posts/2023-04-19-fedora38-whatnew.md
> +- 最新的 Linux kernel 6.2 版本带来了扩展的硬件支持、错误修复和性能改进。
kernel: 内核

2023-04-20 00:54 UTC, alick commented on _posts/2023-04-19-fedora38-whatnew.md
> +- Fedora 38 的分析将更容易，这要归功于其[默认构建配置的更改][change]。我们期望这将促进未来版本的性能改进。
分析：程序/软件性能分析
归功于其：去掉其

2023-04-20 00:54 UTC, alick commented on _posts/2023-04-19-fedora38-whatnew.md
> +## 还要看看……
此外还有……/其他亮点/

2023-04-20 01:51 UTC, Hanjingxue-Boling commented on _posts/2023-04-19-fedora38-released.md
> +当然，我们生产的不仅仅是 Edition。[Fedora Spins][spin] 和 [Labs][lab] 面向各种受众和用例，包括为计算神经科学提供工具的 [Fedora Comp Neuro]，以及提供轻量级桌面环境的 [Fedora LXQt] 等桌面环境。而且，不要忘记我们的备用架构：[ARM AArch64、Power 和 S390x][alt]。
OK

2023-04-20 01:52 UTC, Hanjingxue-Boling commented on _posts/2023-04-19-fedora38-released.md
> +我们很高兴你能试用新版本！请转到 <https://fedoraproject.org/> 并立即下载。如果你已经在运行 Fedora Linux，请按照[简单的升级说明][upgrading]进行操作。有关 Fedora Linux 38 中新功能的更多信息，请参阅[发行说明]。
done

2023-04-20 01:57 UTC, Hanjingxue-Boling commented on _posts/2023-04-19-fedora38-whatnew.md
> +- 最新的 Linux kernel 6.2 版本带来了扩展的硬件支持、错误修复和性能改进。
这个我一般习惯不翻译，直接用 Linux kernel

2023-04-21 02:30 UTC, alick approved these changes

2023-04-21 02:30 UTC, merged

2023-04-21 02:35 UTC, Hanjingxue-Boling commented
看来生成的样式还是存在一些问题，我再修改一下。 @alick